def _item(finnish, english, grammar_tag, cue):
    return {
        'finnish': finnish,
        'english': english,
        'grammarTag': grammar_tag,
        'cue': cue,
    }


def _lesson(code, level, title, theme, grammar, objectives, items):
    return {
        'id': code.lower().replace(' ', '-'),
        'code': code,
        'level': level,
        'title': title,
        'theme': theme,
        'grammar': grammar,
        'objectives': objectives,
        'skills': ['reading', 'writing', 'speaking', 'listening'],
        'items': items,
    }


LESSON_DATABASE = {
    'version': '2026-04-a1-a2',
    'language': 'fi_FI',
    'title': 'Finnish A1-A2 Lesson Bank',
    'lessons': [
        _lesson(
            'A1-01-greetings-introductions',
            'A1',
            'Greetings and Introductions',
            'Meeting people and basic politeness',
            ['basic greetings', 'name questions', 'copula olla'],
            ['Greet people politely', 'Say your name and origin', 'Handle simple introductions'],
            [
                _item('Hei!', 'Hi!', 'polite', 'Use this to greet someone in a neutral way.'),
                _item('Moi!', 'Hey!', 'polite', 'Use this with friends and classmates.'),
                _item('Hyvää huomenta!', 'Good morning!', 'time', 'Say this in the morning.'),
                _item('Mitä kuuluu?', 'How are you?', 'question', 'Ask how another person is doing.'),
                _item('Minun nimeni on Anna.', 'My name is Anna.', 'verb-form', 'Introduce yourself.'),
                _item('Hauska tavata.', 'Nice to meet you.', 'polite', 'Say this in a first meeting.'),
                _item('Olen Suomesta.', 'I am from Finland.', 'verb-form', 'Say where you are from.'),
                _item('Nähdään huomenna.', 'See you tomorrow.', 'time', 'End a meeting politely.'),
            ],
        ),
        _lesson(
            'A1-02-classroom-basics',
            'A1',
            'Classroom Basics',
            'Simple classroom interaction and requests',
            ['question forms', 'need expressions', 'please and thanks'],
            ['Understand classroom language', 'Ask basic questions', 'Make polite requests'],
            [
                _item('Voitko toistaa?', 'Can you repeat?', 'question', 'Ask the teacher to repeat.'),
                _item('En ymmärrä.', 'I do not understand.', 'verb-form', 'Say this when something is unclear.'),
                _item('Ymmärrän nyt.', 'I understand now.', 'verb-form', 'Say this after clarification.'),
                _item('Tarvitsen kynän.', 'I need a pen.', 'other', 'Ask for a classroom item.'),
                _item('Missä kirja on?', 'Where is the book?', 'question', 'Ask where something is.'),
                _item('Avaa kirja.', 'Open the book.', 'other', 'Recognize a simple classroom instruction.'),
                _item('Kirjoita tähän.', 'Write here.', 'other', 'Recognize a writing instruction.'),
                _item('Kiitos avusta.', 'Thanks for the help.', 'polite', 'Thank someone in class.'),
            ],
        ),
        _lesson(
            'A1-03-family-and-people',
            'A1',
            'Family and People',
            'Talking about family members and basic descriptions',
            ['possessive-like expressions', 'have structures', 'basic adjectives'],
            ['Name family members', 'Say who is in your family', 'Describe people simply'],
            [
                _item('Tämä on äitini.', 'This is my mother.', 'other', 'Introduce a family member.'),
                _item('Minulla on yksi veli.', 'I have one brother.', 'other', 'Say how many siblings you have.'),
                _item('Sisareni asuu Turussa.', 'My sister lives in Turku.', 'verb-form', 'Say where a relative lives.'),
                _item('Isoisäni on eläkkeellä.', 'My grandfather is retired.', 'verb-form', 'Describe an older relative.'),
                _item('Hän on ystävällinen.', 'He or she is friendly.', 'verb-form', 'Describe someone positively.'),
                _item('Kuinka vanha hän on?', 'How old is he or she?', 'question', 'Ask someone’s age.'),
                _item('Hän on kaksikymmentä vuotta vanha.', 'He or she is twenty years old.', 'other', 'Answer an age question.'),
                _item('Me olemme suuri perhe.', 'We are a big family.', 'verb-form', 'Talk about your family size.'),
            ],
        ),
        _lesson(
            'A1-04-numbers-time-dates',
            'A1',
            'Numbers, Time, and Dates',
            'Telling time and talking about schedules',
            ['time expressions', 'numbers', 'calendar words'],
            ['Tell the time', 'Ask for dates', 'Understand simple schedules'],
            [
                _item('Kello on kaksi.', 'It is two o’clock.', 'time', 'Tell the time in a simple way.'),
                _item('Kurssi alkaa yhdeksältä.', 'The course starts at nine.', 'time', 'Say when something starts.'),
                _item('Mikä päivä tänään on?', 'What day is it today?', 'question', 'Ask for the day.'),
                _item('Tänään on maanantai.', 'Today is Monday.', 'time', 'Answer with the day.'),
                _item('Huomenna on vapaa päivä.', 'Tomorrow is a day off.', 'time', 'Talk about tomorrow.'),
                _item('Minun syntymäpäiväni on toukokuussa.', 'My birthday is in May.', 'time', 'Say the month of your birthday.'),
                _item('Paljonko tämä maksaa?', 'How much does this cost?', 'question', 'Use this with numbers and prices.'),
                _item('Se maksaa kymmenen euroa.', 'It costs ten euros.', 'other', 'Answer with a price.'),
            ],
        ),
        _lesson(
            'A1-05-food-and-drink',
            'A1',
            'Food and Drink',
            'Basic meals, preferences, and simple orders',
            ['partitive basics', 'likes and dislikes', 'meal vocabulary'],
            ['Name common foods', 'Say what you want', 'Talk about meals simply'],
            [
                _item('Haluan kahvia.', 'I want coffee.', 'partitive', 'Order a drink.'),
                _item('Syön aamulla puuroa.', 'I eat porridge in the morning.', 'partitive', 'Talk about breakfast.'),
                _item('Pidän teestä.', 'I like tea.', 'other', 'Say what drink you like.'),
                _item('En pidä kalasta.', 'I do not like fish.', 'partitive', 'Say what food you do not like.'),
                _item('Otatko leipää?', 'Would you like some bread?', 'question', 'Offer food politely.'),
                _item('Kiitos, otan vähän.', 'Thanks, I will take a little.', 'polite', 'Accept an offer politely.'),
                _item('Missä maito on?', 'Where is the milk?', 'question', 'Ask where a food item is.'),
                _item('Illalla juon vettä.', 'In the evening I drink water.', 'time', 'Describe an evening habit.'),
            ],
        ),
        _lesson(
            'A1-06-shopping-and-money',
            'A1',
            'Shopping and Money',
            'Simple buying situations in shops and markets',
            ['questions in shops', 'numbers and prices', 'polite requests'],
            ['Ask for items', 'Understand prices', 'Handle basic purchases'],
            [
                _item('Etsin talvitakkia.', 'I am looking for a winter coat.', 'other', 'Say what you are looking for.'),
                _item('Onko teillä tätä kokoa?', 'Do you have this size?', 'question', 'Ask about clothing size.'),
                _item('Haluaisin maksaa kortilla.', 'I would like to pay by card.', 'polite', 'Say how you want to pay.'),
                _item('Kuitti, kiitos.', 'Receipt, please.', 'polite', 'Ask for the receipt.'),
                _item('Tämä on liian kallis.', 'This is too expensive.', 'other', 'React to a price.'),
                _item('Voinko sovittaa tätä?', 'Can I try this on?', 'question', 'Ask in a clothes shop.'),
                _item('Tarvitsen uuden repun.', 'I need a new backpack.', 'other', 'Say what item you need.'),
                _item('Ale alkaa huomenna.', 'The sale starts tomorrow.', 'time', 'Talk about a shop event.'),
            ],
        ),
        _lesson(
            'A1-07-home-and-rooms',
            'A1',
            'Home and Rooms',
            'Talking about where you live and what is at home',
            ['place expressions', 'there is', 'room vocabulary'],
            ['Describe your home', 'Name rooms and furniture', 'Ask where things are'],
            [
                _item('Asun pienessä asunnossa.', 'I live in a small apartment.', 'other', 'Describe where you live.'),
                _item('Keittiö on valoisa.', 'The kitchen is bright.', 'verb-form', 'Describe a room.'),
                _item('Missä kylpyhuone on?', 'Where is the bathroom?', 'question', 'Ask for a room.'),
                _item('Sohva on olohuoneessa.', 'The sofa is in the living room.', 'other', 'Say where a piece of furniture is.'),
                _item('Minulla on oma huone.', 'I have my own room.', 'other', 'Talk about your room.'),
                _item('Pöytä on ikkunan vieressä.', 'The table is next to the window.', 'other', 'Describe location in a room.'),
                _item('Kotona on hiljaista.', 'It is quiet at home.', 'verb-form', 'Describe the atmosphere at home.'),
                _item('Siivoan huomenna.', 'I will clean tomorrow.', 'time', 'Talk about a home task.'),
            ],
        ),
        _lesson(
            'A1-08-daily-routine',
            'A1',
            'Daily Routine',
            'Talking about everyday actions and schedules',
            ['present tense', 'time words', 'routine verbs'],
            ['Describe your day', 'Talk about work or study times', 'Say what you do every day'],
            [
                _item('Herään seitsemältä.', 'I wake up at seven.', 'time', 'Talk about the start of your day.'),
                _item('Pesen hampaat aamulla.', 'I brush my teeth in the morning.', 'time', 'Describe a morning routine.'),
                _item('Menen töihin bussilla.', 'I go to work by bus.', 'verb-form', 'Say how you commute.'),
                _item('Syömme lounaan kahdeltatoista.', 'We eat lunch at twelve.', 'time', 'Talk about lunch time.'),
                _item('Teen kotitehtävät illalla.', 'I do homework in the evening.', 'time', 'Talk about evening study.'),
                _item('Milloin menet nukkumaan?', 'When do you go to sleep?', 'question', 'Ask about sleep time.'),
                _item('Luemme uutisia joka päivä.', 'We read news every day.', 'verb-form', 'Describe a daily habit.'),
                _item('Viikonloppuna lepään.', 'At the weekend I rest.', 'time', 'Talk about your weekend routine.'),
            ],
        ),
        _lesson(
            'A1-09-town-and-directions',
            'A1',
            'Town and Directions',
            'Navigating simple places in town',
            ['place questions', 'direction words', 'public places'],
            ['Ask where places are', 'Understand simple directions', 'Move around town'],
            [
                _item('Missä asema on?', 'Where is the station?', 'question', 'Ask where a place is.'),
                _item('Pankki on tuolla vasemmalla.', 'The bank is over there on the left.', 'other', 'Understand a basic direction.'),
                _item('Käänny oikealle.', 'Turn right.', 'other', 'Follow a direction.'),
                _item('Mene suoraan eteenpäin.', 'Go straight ahead.', 'other', 'Follow a simple route instruction.'),
                _item('Kirjasto on torin vieressä.', 'The library is next to the square.', 'other', 'Locate a place in town.'),
                _item('Kuinka pääsen sairaalaan?', 'How do I get to the hospital?', 'question', 'Ask for directions politely.'),
                _item('Bussi pysähtyy tässä.', 'The bus stops here.', 'verb-form', 'Understand transport information.'),
                _item('Olemme nyt keskustassa.', 'We are now in the city centre.', 'verb-form', 'Say where you are.'),
            ],
        ),
        _lesson(
            'A1-10-weather-and-seasons',
            'A1',
            'Weather and Seasons',
            'Talking about weather and clothes for seasons',
            ['weather expressions', 'time words', 'adjectives'],
            ['Describe today’s weather', 'Talk about seasons', 'Choose suitable clothing'],
            [
                _item('Tänään on aurinkoista.', 'It is sunny today.', 'time', 'Describe today’s weather.'),
                _item('Ulkona sataa lunta.', 'It is snowing outside.', 'other', 'Describe winter weather.'),
                _item('On kylmä ja tuulinen.', 'It is cold and windy.', 'verb-form', 'Combine two weather adjectives.'),
                _item('Kesällä on lämmin.', 'In summer it is warm.', 'time', 'Talk about a season.'),
                _item('Tarvitsen sateenvarjon.', 'I need an umbrella.', 'other', 'Say what you need in rainy weather.'),
                _item('Mikä sää huomenna on?', 'What is the weather like tomorrow?', 'question', 'Ask about tomorrow’s weather.'),
                _item('Keväällä päivät pitenevät.', 'In spring the days get longer.', 'time', 'Describe a spring change.'),
                _item('Puen lämpimän takin.', 'I put on a warm coat.', 'other', 'Talk about clothing for the weather.'),
            ],
        ),
        _lesson(
            'A2-01-hobbies-and-free-time',
            'A2',
            'Hobbies and Free Time',
            'Talking about interests, frequency, and preferences',
            ['frequency words', 'verb choices', 'opinions'],
            ['Describe hobbies', 'Say how often you do things', 'Invite others to activities'],
            [
                _item('Harrastan joogaa kahdesti viikossa.', 'I do yoga twice a week.', 'time', 'Talk about hobby frequency.'),
                _item('Pidän erityisesti musiikista.', 'I especially like music.', 'other', 'Express a clear preference.'),
                _item('Luen usein romaaneja.', 'I often read novels.', 'partitive', 'Describe a reading habit.'),
                _item('Käymmekö yhdessä uimassa?', 'Shall we go swimming together?', 'question', 'Invite someone to an activity.'),
                _item('Minulla ei ole paljon vapaa-aikaa.', 'I do not have much free time.', 'other', 'Talk about your schedule.'),
                _item('Pelaan jalkapalloa ystävien kanssa.', 'I play football with friends.', 'partitive', 'Talk about a social hobby.'),
                _item('Viikonloppuna katson elokuvan.', 'At the weekend I watch a film.', 'time', 'Talk about weekend entertainment.'),
                _item('Se auttaa minua rentoutumaan.', 'It helps me relax.', 'verb-form', 'Explain why you like a hobby.'),
            ],
        ),
        _lesson(
            'A2-02-health-and-body',
            'A2',
            'Health and the Body',
            'Describing symptoms and giving simple advice',
            ['body vocabulary', 'need and should expressions', 'questions at a clinic'],
            ['Describe how you feel', 'Name body parts and symptoms', 'Understand simple advice'],
            [
                _item('Minulla on päänsärkyä.', 'I have a headache.', 'partitive', 'Describe a common symptom.'),
                _item('Kurkkuni on kipeä.', 'My throat is sore.', 'verb-form', 'Describe throat pain.'),
                _item('Tarvitsen lääkärin ajan.', 'I need a doctor’s appointment.', 'other', 'Ask for medical help.'),
                _item('Missä terveyskeskus on?', 'Where is the health centre?', 'question', 'Ask where to go for help.'),
                _item('Sinun pitää levätä.', 'You need to rest.', 'verb-form', 'Understand simple advice.'),
                _item('Olen allerginen pähkinöille.', 'I am allergic to nuts.', 'verb-form', 'Give important health information.'),
                _item('Kuume nousi eilen illalla.', 'The fever rose yesterday evening.', 'time', 'Describe when a symptom started.'),
                _item('Voinko saada reseptin?', 'Can I get a prescription?', 'question', 'Ask for medicine formally.'),
            ],
        ),
        _lesson(
            'A2-03-restaurant-and-cafe',
            'A2',
            'Restaurant and Cafe',
            'Ordering food, asking for recommendations, and handling problems',
            ['polite requests', 'food descriptions', 'questions in service situations'],
            ['Order politely', 'Ask about the menu', 'React to simple restaurant issues'],
            [
                _item('Saisinko ruokalistan?', 'Could I have the menu?', 'polite', 'Ask for the menu politely.'),
                _item('Mikä on päivän keitto?', 'What is the soup of the day?', 'question', 'Ask about today’s special.'),
                _item('Ottaisin lohta ja salaattia.', 'I will take salmon and salad.', 'partitive', 'Place an order.'),
                _item('Tämä annos on todella hyvä.', 'This portion is really good.', 'other', 'Give positive feedback.'),
                _item('Voisinko saada vettä lisää?', 'Could I get more water?', 'polite', 'Ask for something extra.'),
                _item('Ruoka tuli nopeasti.', 'The food came quickly.', 'verb-form', 'Comment on service speed.'),
                _item('Lasku, kiitos.', 'The bill, please.', 'polite', 'Ask to pay.'),
                _item('Tässä ruoassa on liikaa suolaa.', 'There is too much salt in this food.', 'other', 'Politely describe a problem.'),
            ],
        ),
        _lesson(
            'A2-04-travel-and-transport',
            'A2',
            'Travel and Transport',
            'Planning trips and moving between places',
            ['travel vocabulary', 'time and schedules', 'booking questions'],
            ['Buy tickets', 'Understand transport times', 'Talk about a trip'],
            [
                _item('Tarvitsen lipun Helsinkiin.', 'I need a ticket to Helsinki.', 'other', 'Buy a ticket.'),
                _item('Milloin seuraava juna lähtee?', 'When does the next train leave?', 'question', 'Ask about a departure.'),
                _item('Matka kestää kaksi tuntia.', 'The trip takes two hours.', 'time', 'Talk about duration.'),
                _item('Vaihdan bussia keskustassa.', 'I change buses in the city centre.', 'verb-form', 'Explain your route.'),
                _item('Missä lähtölaituri on?', 'Where is the departure platform?', 'question', 'Ask at a station.'),
                _item('Olen varannut hotellin valmiiksi.', 'I have booked the hotel already.', 'verb-form', 'Talk about travel preparation.'),
                _item('Lentoni on myöhässä.', 'My flight is late.', 'verb-form', 'Describe a travel problem.'),
                _item('Saavumme perille illalla.', 'We arrive in the evening.', 'time', 'Say when you arrive.'),
            ],
        ),
        _lesson(
            'A2-05-work-and-study',
            'A2',
            'Work and Study',
            'Talking about your job, studies, and responsibilities',
            ['present tense at work', 'have to expressions', 'schedule language'],
            ['Describe your work or studies', 'Talk about tasks', 'Ask practical questions'],
            [
                _item('Opiskelen suomea iltakurssilla.', 'I study Finnish in an evening course.', 'verb-form', 'Describe where you study.'),
                _item('Työskentelen toimistossa.', 'I work in an office.', 'verb-form', 'Describe your workplace.'),
                _item('Minulla on kokous aamupäivällä.', 'I have a meeting in the late morning.', 'time', 'Talk about your schedule.'),
                _item('Teen paljon ryhmätöitä.', 'I do a lot of group work.', 'partitive', 'Describe a common task.'),
                _item('Milloin tehtävä pitää palauttaa?', 'When must the assignment be returned?', 'question', 'Ask about a deadline.'),
                _item('Tarvitsen lisää aikaa.', 'I need more time.', 'other', 'Say you need more time.'),
                _item('Harjoittelen puhumista joka päivä.', 'I practise speaking every day.', 'verb-form', 'Describe language learning.'),
                _item('Työpäivä loppuu viideltä.', 'The workday ends at five.', 'time', 'Say when work finishes.'),
            ],
        ),
        _lesson(
            'A2-06-making-plans',
            'A2',
            'Making Plans',
            'Agreeing on times, places, and social activities',
            ['future-oriented expressions', 'questions', 'polite invitations'],
            ['Make simple plans', 'Arrange meetings', 'Accept or decline politely'],
            [
                _item('Tavataanko kahvilassa kuudelta?', 'Shall we meet at the cafe at six?', 'question', 'Suggest a meeting.'),
                _item('Se sopii minulle hyvin.', 'That suits me well.', 'other', 'Accept a plan politely.'),
                _item('Valitettavasti en pääse.', 'Unfortunately I cannot come.', 'polite', 'Decline politely.'),
                _item('Voimmeko siirtää tapaamisen?', 'Can we move the meeting?', 'question', 'Ask to change a plan.'),
                _item('Lähetän sinulle viestin myöhemmin.', 'I will send you a message later.', 'time', 'Promise to follow up.'),
                _item('Mennään yhdessä kävelylle.', 'Let us go for a walk together.', 'other', 'Make a simple suggestion.'),
                _item('Minulla on muuta ohjelmaa silloin.', 'I have other plans then.', 'time', 'Explain why you are busy.'),
                _item('Nähdään ensi viikolla.', 'See you next week.', 'time', 'Confirm a future plan.'),
            ],
        ),
        _lesson(
            'A2-07-describing-people',
            'A2',
            'Describing People',
            'Talking about appearance, character, and habits',
            ['adjectives', 'comparison basics', 'habit expressions'],
            ['Describe people clearly', 'Talk about personality', 'Compare simple traits'],
            [
                _item('Hän on melko rauhallinen.', 'He or she is fairly calm.', 'verb-form', 'Describe personality softly.'),
                _item('Ystäväni on hyvin puhelias.', 'My friend is very talkative.', 'verb-form', 'Describe how someone speaks.'),
                _item('Opettaja on kärsivällinen.', 'The teacher is patient.', 'verb-form', 'Describe a positive quality.'),
                _item('Hänellä on ruskeat hiukset.', 'He or she has brown hair.', 'other', 'Describe appearance.'),
                _item('Veljeni on minua pidempi.', 'My brother is taller than me.', 'other', 'Make a basic comparison.'),
                _item('Millainen uusi naapuri on?', 'What is the new neighbour like?', 'question', 'Ask about a person.'),
                _item('Hän puhuu aina hitaasti.', 'He or she always speaks slowly.', 'time', 'Describe a speaking habit.'),
                _item('Pidän hänen huumoristaan.', 'I like his or her sense of humour.', 'other', 'Say what you like in a person.'),
            ],
        ),
        _lesson(
            'A2-08-services-and-problems',
            'A2',
            'Services and Problems',
            'Handling common issues in everyday services',
            ['problem descriptions', 'help requests', 'service questions'],
            ['Explain a simple problem', 'Ask for help', 'Understand practical service talk'],
            [
                _item('Internet ei toimi kotona.', 'The internet does not work at home.', 'verb-form', 'Describe a home service problem.'),
                _item('Tarvitsen apua tämän lomakkeen kanssa.', 'I need help with this form.', 'other', 'Ask for practical help.'),
                _item('Missä voin tulostaa tämän?', 'Where can I print this?', 'question', 'Ask where to use a service.'),
                _item('Paketti ei ole tullut vielä.', 'The package has not arrived yet.', 'time', 'Describe a delivery problem.'),
                _item('Voitteko tarkistaa asian?', 'Can you check the matter?', 'question', 'Ask customer service politely.'),
                _item('Korttini ei toimi automaatissa.', 'My card does not work in the machine.', 'verb-form', 'Describe a payment problem.'),
                _item('Sain väärän laskun.', 'I got the wrong bill.', 'verb-form', 'Explain an invoicing issue.'),
                _item('Kiitos, ongelma ratkesi.', 'Thank you, the problem was solved.', 'polite', 'Close the service situation positively.'),
            ],
        ),
        _lesson(
            'A2-09-feelings-and-opinions',
            'A2',
            'Feelings and Opinions',
            'Expressing reactions, preferences, and simple reasons',
            ['opinion phrases', 'emotion vocabulary', 'because clauses'],
            ['State your opinion', 'Describe your mood', 'Give simple reasons'],
            [
                _item('Minusta tämä idea on hyvä.', 'I think this idea is good.', 'other', 'Give a positive opinion.'),
                _item('Olen vähän väsynyt tänään.', 'I am a little tired today.', 'time', 'Describe your mood today.'),
                _item('Se kuulostaa kiinnostavalta.', 'That sounds interesting.', 'verb-form', 'React to a suggestion.'),
                _item('En ole aivan samaa mieltä.', 'I do not quite agree.', 'other', 'Disagree politely.'),
                _item('Miksi pidät tästä kirjasta?', 'Why do you like this book?', 'question', 'Ask for a reason.'),
                _item('Pidän siitä, koska se on hauska.', 'I like it because it is fun.', 'other', 'Give a simple reason.'),
                _item('Olen iloinen onnistumisesta.', 'I am happy about the success.', 'verb-form', 'Describe a positive feeling.'),
                _item('Tilanne tuntuu vaikealta.', 'The situation feels difficult.', 'verb-form', 'Describe a challenging situation.'),
            ],
        ),
        _lesson(
            'A2-10-home-life-and-review',
            'A2',
            'Home Life and Review',
            'Mixed review of daily life, chores, and short experiences',
            ['routine review', 'past reference with time words', 'practical home language'],
            ['Consolidate A1-A2 topics', 'Talk about recent daily experiences', 'Use home-life vocabulary actively'],
            [
                _item('Eilen siivosin koko keittiön.', 'Yesterday I cleaned the whole kitchen.', 'time', 'Talk about a recent chore.'),
                _item('Tänään teen pyykkiä ja ruokaa.', 'Today I do laundry and make food.', 'time', 'Describe home tasks for today.'),
                _item('Huomenna tulee vieraita.', 'Guests are coming tomorrow.', 'time', 'Talk about future home plans.'),
                _item('Jääkaapissa ei ole maitoa.', 'There is no milk in the fridge.', 'other', 'Describe something missing at home.'),
                _item('Voisitko auttaa minua kantamaan tämän?', 'Could you help me carry this?', 'question', 'Ask for help at home.'),
                _item('Pidimme eilen rauhallisen illan.', 'We had a calm evening yesterday.', 'time', 'Describe a recent evening.'),
                _item('Minun pitää ostaa lamppu olohuoneeseen.', 'I need to buy a lamp for the living room.', 'other', 'Talk about improving your home.'),
                _item('Arki sujuu nyt paremmin.', 'Daily life goes better now.', 'verb-form', 'Reflect on your progress in daily life.'),
            ],
        ),
    ],
}


def _generate_synthetic_lessons(target_total=620):
    """Create extra deterministic lessons to scale catalog size for broad practice."""
    existing_lessons = LESSON_DATABASE['lessons']
    if len(existing_lessons) >= target_total:
        return []

    starter_templates = [
        {
            'theme': 'School and Study Routines',
            'grammar': ['present tense', 'questions', 'time expressions'],
            'objectives': ['Talk about school day flow', 'Ask and answer classroom questions', 'Build routine fluency'],
            'items': [
                ('Menen kouluun aikaisin.', 'I go to school early.', 'time', 'Describe school routine timing.'),
                ('Opettaja selittää asian selvästi.', 'The teacher explains the topic clearly.', 'verb-form', 'Describe lesson clarity.'),
                ('Milloin tunti alkaa?', 'When does the lesson start?', 'question', 'Ask about start time.'),
                ('Kirjoitan muistiinpanoja vihkoon.', 'I write notes in a notebook.', 'other', 'Describe note-taking.'),
                ('Teemme harjoituksia ryhmässä.', 'We do exercises in a group.', 'verb-form', 'Describe group work.'),
                ('Tarvitsen lisää aikaa tähän tehtävään.', 'I need more time for this task.', 'other', 'Ask for extra time.'),
                ('Ymmärsin aiheen paremmin tänään.', 'I understood the topic better today.', 'time', 'Reflect on progress.'),
                ('Voitko tarkistaa vastaukseni?', 'Can you check my answer?', 'question', 'Ask for feedback politely.'),
            ],
        },
        {
            'theme': 'Daily Communication',
            'grammar': ['polite requests', 'questions', 'opinions'],
            'objectives': ['Handle common conversations', 'Respond politely', 'Share simple opinions'],
            'items': [
                ('Voimmeko puhua hetken?', 'Can we talk for a moment?', 'question', 'Start a short conversation.'),
                ('Kiitos viestistäsi.', 'Thank you for your message.', 'polite', 'Acknowledge a message politely.'),
                ('Mitä mieltä olet tästä?', 'What do you think about this?', 'question', 'Ask for an opinion.'),
                ('Minusta suunnitelma toimii hyvin.', 'I think the plan works well.', 'other', 'Give positive feedback.'),
                ('Tarvitsetko apua nyt?', 'Do you need help now?', 'question', 'Offer support.'),
                ('Voin vastata myöhemmin.', 'I can reply later.', 'time', 'Delay politely.'),
                ('Yritän selittää tämän yksinkertaisesti.', 'I try to explain this simply.', 'verb-form', 'Clarify communication.'),
                ('Sovitaan uusi aika huomiseksi.', 'Let us agree on a new time for tomorrow.', 'time', 'Arrange next contact.'),
            ],
        },
        {
            'theme': 'Practical City Life',
            'grammar': ['place expressions', 'service questions', 'time words'],
            'objectives': ['Move through city contexts', 'Handle basic services', 'Express practical needs'],
            'items': [
                ('Menen keskustaan bussilla.', 'I go to the city centre by bus.', 'verb-form', 'Describe city travel.'),
                ('Missä lähin apteekki on?', 'Where is the nearest pharmacy?', 'question', 'Ask for local services.'),
                ('Tarvitsen lipun kahdeksi päiväksi.', 'I need a ticket for two days.', 'other', 'Ask for a time-based ticket.'),
                ('Pysähdymme seuraavalla asemalla.', 'We stop at the next station.', 'time', 'Understand trip progress.'),
                ('Palvelu oli tänään nopeaa.', 'The service was fast today.', 'time', 'Comment on service quality.'),
                ('Voinko maksaa puhelimella?', 'Can I pay with a phone?', 'question', 'Ask about payment methods.'),
                ('Lähetän palautteen illalla.', 'I will send feedback in the evening.', 'time', 'Plan follow-up action.'),
                ('Kaikki sujui lopulta hyvin.', 'Everything went well in the end.', 'verb-form', 'Summarize the outcome.'),
            ],
        },
    ]

    generated = []
    index = 1
    while len(existing_lessons) + len(generated) < target_total:
        template = starter_templates[(index - 1) % len(starter_templates)]
        level = 'A1' if index % 2 else 'A2'
        code = f'{level}-X{index:03d}-practice-pack'
        title = f'{template["theme"]} Pack {index:03d}'

        items = []
        for row, row_data in enumerate(template['items'], start=1):
            finnish, english, grammar_tag, cue = row_data
            items.append(_item(
                f'{finnish} (set {index:03d}-{row})',
                f'{english} (set {index:03d}-{row})',
                grammar_tag,
                cue,
            ))

        generated.append(_lesson(
            code,
            level,
            title,
            f'{template["theme"]} extended drilling set',
            template['grammar'],
            template['objectives'],
            items,
        ))
        index += 1

    return generated


LESSON_DATABASE['lessons'].extend(_generate_synthetic_lessons(620))
LESSON_DATABASE['version'] = '2026-04-expanded-620'
LESSON_DATABASE['title'] = 'Finnish A1-A2 Lesson Bank (Expanded)'